name: GitHub Actions Demo
on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: "15 6 * * *"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.event.workflow_run.head_branch }}
      - run: ls
